dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcol-custom
  description: Custom OpenTelemetry Collector Contrib
  output_path: ./dist
  version: 0.141.0

receivers:
    - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.141.0

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.141.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.141.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.141.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.141.0

connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector v0.141.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.141.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.141.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.141.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.47.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.47.0
